### ISSUE TITLE
Deadlock with readerwriterqueue when spinning over try_enqueue() method

### ISSUE THREAD

**Issue by f18m** [cameron314/readerwriterqueue#139]
Hi,
I've been integrating the readerwriterqueue (which is amazing, thanks!!) but I'm hitting some problem when, inside a benchmark test, I spin a producer and a consumer thread and then the producer spins like crazy over the try_enqueue() method.
Please note that my target is to have the queue of a fixed size and I'm not interested in having dynamic allocations so that's why I use try_enqueue().

I aligned with latest release 1.0.6 and built the code in debug mode.
The benchmark test is designed to spin the producer and consumer threads (as pthreads), wait 5 seconds, then it changes a std::atomic<bool> that is constantly checked by the "event loop" of the threads from false to true to request the thread to exit.
What happens is that the CONSUMER thread (which is invoking peek() + try_dequeue()) exits correctly.
Then PRODUCER thread (which is charge of creating fake into a structure named "HwIPacket_s") instead is spinning at 100% and never exits, because the moodycamel try_enqueue() never releases the control back to the caller (so the thread will not check that the std::atomic<bool> flag I use to ask thread to terminate).

Here is the GDB output of the thread that is spinning at 100% of cpu, blocked apparently on the 'moodycamel::weak_atomic<bool>::operator=<bool>' (which seems so strange to me):

```
# gdb ./InterThreadQueueBenchmark_D  

GNU gdb (GDB) Fedora 12.1-1.fc35
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Bin/docker-debug/InterThreadQueueBenchmark_D...
(gdb) r
Starting program: /source/Capture/Engine/Benchmarks/InterThreadQueue/Bin/docker-debug/InterThreadQueueBenchmark_D
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
main(): start of benchmarks

main(): TESTING INTERTHREAD QUEUE
main(): sleeping in each test for 5secs

** Running benchmark with 1 threads as producer threads with producer behavior = [SPIN WHEN FULL]
  Starting enqueuer 00 on cpu 0
  Starting dequeuer 00 on cpu 1
  
 # here I type CTRL+C because the software gets stuck here forever
^C
Thread 1 "InterThreadQueu" received signal SIGINT, Interrupt.
0x00007ffff09c33ba in __futex_abstimed_wait_common () from /lib64/libc.so.6
(gdb) info threads
  Id   Target Id                                          Frame
* 1    Thread 0x7fffeed41500 (LWP 9776) "InterThreadQueu" 0x00007ffff09c33ba in __futex_abstimed_wait_common () from /lib64/libc.so.6
  2    Thread 0x7fffea7ff640 (LWP 9779) "InterThreadQueu" 0x000000000095c10a in moodycamel::weak_atomic<bool>::operator=<bool> (this=0x616000020b10,
    x=@0x7fffea7f1b50: false)
    at /opt/empirix/conan/third-party-cpp-libs/3.17.1+develop-2/empirix/stable/package/9bf803d1df8be2bb2c6f54e13784fe1b8648fc2d/include/atomicops.h:311
(gdb) thread 2
[Switching to thread 2 (Thread 0x7fffea7ff640 (LWP 9779))]
#0  0x000000000095c10a in moodycamel::weak_atomic<bool>::operator=<bool> (this=0x616000020b10, x=@0x7fffea7f1b50: false)
    at /opt/empirix/conan/third-party-cpp-libs/3.17.1+develop-2/empirix/stable/package/9bf803d1df8be2bb2c6f54e13784fe1b8648fc2d/include/atomicops.h:311
311             }
(gdb) bt
#0  0x000000000095c10a in moodycamel::weak_atomic<bool>::operator=<bool> (this=0x616000020b10, x=@0x7fffea7f1b50: false)
    at /opt/empirix/conan/third-party-cpp-libs/3.17.1+develop-2/empirix/stable/package/9bf803d1df8be2bb2c6f54e13784fe1b8648fc2d/include/atomicops.h:311
#1  0x000000000095b368 in moodycamel::ReaderWriterQueue<HwIPacket_s, 512ul>::ReentrantGuard::~ReentrantGuard (this=0x7fffea7f1c00, __in_chrg=<optimized out>)
    at /opt/empirix/conan/third-party-cpp-libs/3.17.1+develop-2/empirix/stable/package/9bf803d1df8be2bb2c6f54e13784fe1b8648fc2d/include/readerwriterqueue.h:685
#2  0x000000000095a670 in moodycamel::ReaderWriterQueue<HwIPacket_s, 512ul>::inner_enqueue<(moodycamel::ReaderWriterQueue<HwIPacket_s, 512ul>::AllocationMode)1, HwIPacket_s c                                                            onst&> (this=0x616000020ac0)
    at /opt/empirix/conan/third-party-cpp-libs/3.17.1+develop-2/empirix/stable/package/9bf803d1df8be2bb2c6f54e13784fe1b8648fc2d/include/readerwriterqueue.h:644
#3  0x0000000000957c2f in moodycamel::ReaderWriterQueue<HwIPacket_s, 512ul>::try_enqueue (this=0x616000020ac0, element=...)
    at /opt/empirix/conan/third-party-cpp-libs/3.17.1+develop-2/empirix/stable/package/9bf803d1df8be2bb2c6f54e13784fe1b8648fc2d/include/readerwriterqueue.h:236
#4  0x0000000000957c55 in moodycamel::BlockingReaderWriterQueue<HwIPacket_s, 512ul>::try_enqueue (this=0x616000020ac0, element=...)
    at /opt/empirix/conan/third-party-cpp-libs/3.17.1+develop-2/empirix/stable/package/9bf803d1df8be2bb2c6f54e13784fe1b8648fc2d/include/readerwriterqueue.h:786
#5  0x00000000009554d3 in HwEmulInterThreadQueue::enqueue_deep_copy (this=0x7fffffffdd60, pkt=0x7fffea7f1f60, thread_id=0) at HwEmulInterThreadQueue.cpp:339
#6  0x00000000006ce41c in ProducerThread::RunThread (this=0x613000001380) at /source/Capture/Engine/Benchmarks/InterThreadQueue/producer.h:76
#7  0x00007ffff57dc9b2 in CHMThread::_RunThread (pParam=0x613000001380) at Thread_Joinable.cpp:80
#8  0x00007ffff09c6822 in start_thread () from /lib64/libc.so.6
#9  0x00007ffff0966314 in clone () from /lib64/libc.so.6
(gdb) f 0
#0  0x000000000095c10a in moodycamel::weak_atomic<bool>::operator=<bool> (this=0x616000020b10, x=@0x7fffea7f1b50: false)
    at /opt/empirix/conan/third-party-cpp-libs/3.17.1+develop-2/empirix/stable/package/9bf803d1df8be2bb2c6f54e13784fe1b8648fc2d/include/atomicops.h:311
311             }
(gdb) l
296     #if defined(_M_AMD64)
297                     else if (sizeof(T) == 8) return _InterlockedExchangeAdd64((long long volatile*)&value, (long long)increment);
298     #endif
299     #else
300     #error Unsupported platform
301     #endif
302                     assert(false && "T must be either a 32 or 64 bit type");
303                     return value;
304             }
305     #else
306             template<typename U>
307             AE_FORCEINLINE weak_atomic const& operator=(U&& x) AE_NO_TSAN
308             {
309                     value.store(std::forward<U>(x), std::memory_order_relaxed);
310                     return *this;
311             }
312
313             AE_FORCEINLINE weak_atomic const& operator=(weak_atomic const& other) AE_NO_TSAN
314             {
315                     value.store(other.value.load(std::memory_order_relaxed), std::memory_order_relaxed);
316                     return *this;
317             }
318
319             AE_FORCEINLINE T load() const AE_NO_TSAN { return value.load(std::memory_order_relaxed); }
320
321             AE_FORCEINLINE T fetch_add_acquire(T increment) AE_NO_TSAN
322             {
323                     return value.fetch_add(increment, std::memory_order_acquire);
324             }
325
(gdb) f 1
#1  0x000000000095b368 in moodycamel::ReaderWriterQueue<HwIPacket_s, 512ul>::ReentrantGuard::~ReentrantGuard (this=0x7fffea7f1c00, __in_chrg=<optimized out>)
    at /opt/empirix/conan/third-party-cpp-libs/3.17.1+develop-2/empirix/stable/package/9bf803d1df8be2bb2c6f54e13784fe1b8648fc2d/include/readerwriterqueue.h:685
685                     AE_NO_TSAN ~ReentrantGuard() { inSection = false; }
(gdb) l
670             {
671                     const std::size_t alignment = std::alignment_of<U>::value;
672                     return ptr + (alignment - (reinterpret_cast<std::uintptr_t>(ptr) % alignment)) % alignment;
673             }
674     private:
675     #ifndef MOODYCAMEL_NDEBUG
676             struct ReentrantGuard
677             {
678                     AE_NO_TSAN ReentrantGuard(weak_atomic<bool>& _inSection)
679                             : inSection(_inSection)
680                     {
681                             assert(!inSection && "Concurrent (or re-entrant) enqueue or dequeue operation detected (only one thread at a time may hold the producer or consumer role)");
682                             inSection = true;
683                     }
684
685                     AE_NO_TSAN ~ReentrantGuard() { inSection = false; }
686
687             private:
688                     ReentrantGuard& operator=(ReentrantGuard const&);
689
690             private:
691                     weak_atomic<bool>& inSection;
692             };
693     #endif
694
695             struct Block
696             {
697                     // Avoid false-sharing by putting highly contended variables on their own cache lines
698                     weak_atomic<size_t> front;      // (Atomic) Elements are read from here
699                     size_t localTail;                       // An uncontended shadow copy of tail, owned by the consumer
(gdb) p *this
$1 = {
  inSection = @0x616000020b10
}
(gdb) f 2
#2  0x000000000095a670 in moodycamel::ReaderWriterQueue<HwIPacket_s, 512ul>::inner_enqueue<(moodycamel::ReaderWriterQueue<HwIPacket_s, 512ul>::AllocationMode)1, HwIPacket_s const&> (this=0x616000020ac0)
    at /opt/empirix/conan/third-party-cpp-libs/3.17.1+develop-2/empirix/stable/package/9bf803d1df8be2bb2c6f54e13784fe1b8648fc2d/include/readerwriterqueue.h:644
644             }
(gdb) l
629
630                                     fence(memory_order_release);
631                                     tailBlock = newBlock;
632                             }
633                             else if (canAlloc == CannotAlloc) {
634                                     // Would have had to allocate a new block to enqueue, but not allowed
635                                     return false;
636                             }
637                             else {
638                                     assert(false && "Should be unreachable code");
639                                     return false;
640                             }
641                     }
642
643                     return true;
644             }
645
646
647             // Disable copying
648             ReaderWriterQueue(ReaderWriterQueue const&) {  }
649
650             // Disable assignment
651             ReaderWriterQueue& operator=(ReaderWriterQueue const&) {  }
652
653
654             AE_FORCEINLINE static size_t ceilToPow2(size_t x)
655             {
656                     // From http://graphics.stanford.edu/~seander/bithacks.html#RoundUpPowerOf2
657                     --x;
658                     x |= x >> 1;
(gdb)
```

What am I missing?
Is there any debug info I can provide? 

thanks a lot for any hint!

**Comment by f18m** [comment]
Sorry my bad, I realized now that the problem in my case is that, when the CONSUMER is stopped first, then the PRODUCER might  fill entirely the queue and, in my test, will start spinning at 100% forever, waiting for queue to gain a free slot.

I think in my code I will need to ensure that the producer is always stopped BEFORE the consumer to avoid such a case... 

closing this ticket
