### ISSUE TITLE
coredump

### ISSUE THREAD

**Issue by chengm349** [cameron314/readerwriterqueue#85]
I use gcc on linux:

g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Program terminated with signal 11, Segmentation fault.
#0  load (__m=std::memory_order_relaxed, this=0x0) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/atomic_base.h:396
396     /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/atomic_base.h: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 libgcc-4.8.5-28.el7.x86_64 libstdc++-4.8.5-28.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) where
#0  load (__m=std::memory_order_relaxed, this=0x0) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/atomic_base.h:396
#1  load (this=0x0) at /fs02/home/mcheng/workspace/Trunk_US/directfeeds/sge2/include/atomicops.h:307
#2  tryWait (this=0x0) at /fs02/home/mcheng/workspace/Trunk_US/directfeeds/sge2/include/atomicops.h:632
#3  wait (this=0x0) at /fs02/home/mcheng/workspace/Trunk_US/directfeeds/sge2/include/atomicops.h:642
#4  wait_dequeue<FT_ADP_LIBRARY::FtOM::CTxnQueue::Item> (result=..., this=<optimized out>)
    at /fs02/home/mcheng/workspace/Trunk_US/directfeeds/sge2/include/readerwriterqueue.h:817
#5  FT_ADP_LIBRARY::FtOM::FtOMTxnStore<std::integral_constant<bool, true>, void>::IOThreadRun (this=0x7f931c0724b8)
    at /fs02/home/jenkins/workspace/Rel-15-1-0_PROD/Rel-15-1-54_c++14/directfeeds/face/FtOMAcceptor/FtOMTxnStore.cpp:61
#6  0x000000000077ff0f in execute_native_thread_routine ()
#7  0x00007f932beb4dd5 in start_thread () from /lib64/libpthread.so.0
#8  0x00007f932a7f0b3d in clone () from /lib64/libc.so.6

where might I use wrongly?

**Comment by chengm349** [comment]
let me check more. please feel free to give your suggestion if it does not take too much of your time.

**Comment by chengm349** [comment]
#0  load (__m=std::memory_order_relaxed, this=0x0) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/atomic_base.h:396
396     /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/atomic_base.h: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 libgcc-4.8.5-28.el7.x86_64 libstdc++-4.8.5-28.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) where
#0  load (__m=std::memory_order_relaxed, this=0x0) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/atomic_base.h:396
#1  load (this=0x0) at /fs02/home/thirdparty/readerwriterqueue/atomicops.h:307
#2  tryWait (this=0x0) at /fs02/home/thirdparty/readerwriterqueue/atomicops.h:632
#3  wait (this=0x0) at /fs02/home/thirdparty/readerwriterqueue/atomicops.h:642
#4  wait_dequeue<FT_ADP_LIBRARY::FtOM::CTxnQueue::Item> (result=..., this=<optimized out>) at /fs02/home/thirdparty/readerwriterqueue/readerwriterqueue.h:817

**Comment by chengm349** [comment]
my build env issue looks like.
